---
# defaults file for oneview_enclosure_group
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_enclosure_group/files/oneview_config.json"
contents: "{{lookup('file','../config/config.json') | from_json}}"