---
galaxy_info:
  role_name: oneview_server_profile_template_facts
  author: Asis Bagga
  description: Ansible role to manage OneView Server Profile Template Facts Resources.
  company: Hewlett Packard Enterprise
  license: Apache
  min_ansible_version: 2.9
  min_python_version: 3.4.2
  platforms: []
  galaxy_tags:
    - ansible
    - hpe-oneview
    - ansible-modules
    - sdk
dependencies: ['oneview_enclosure_group', 'oneview_server_hardware_type', 'oneview_scope_uris']
