---
# defaults file for oneview_network_set
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_network_set/files/oneview_config.json" 
config_file: "{{lookup('file', config)}}"
contents: "{{lookup('file','../config/config.json') | from_json}}"

