---
# defaults file for oneview_network_set
network_name: 'Ansible Test Network Set'
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_network_set/files/oneview_config.json" 
contents: "{{lookup('file', config)}}"
ethernet_network_1_name: 'test-ethernet'
