---
# defaults file for oneview_server_hardware
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_rack_manager/files/oneview_config.json"
contents: "{{lookup('file', '../config/config.json') | from_json}}"