---
galaxy_info:
  role_name: oneview_server_profile_facts
  author: Asis Bagga
  description: Ansible role to manage OneView Server Profile Facts resources.
  company: Hewlett Packard Enterprise
  license: Apache
  min_ansible_version: 5.4.0
  min_python_version: 2.7.9
  platforms: []
  galaxy_tags:
    - ansible
    - hpe-oneview
    - ansible-modules
    - sdk
dependencies: []
