---
# defaults file for oneview_hypervisor_manager

config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_hypervisor_manager/files/oneview_config.json"
contents: "{{lookup('file','../config/config.json')|from_json}}"
config_file: "{{lookup('file', config)}}"