---
galaxy_info:
  role_name: oneview_sas_logical_jbod
  author: Alisha K
  description: Ansible role to manage OneView SAS Logical JBOD resources.
  company: Hewlett Packard Enterprise
  license: Apache
  min_ansible_version: 2.9
  min_python_version: 2.7.9
  platforms: []
  galaxy_tags:
    - ansible
    - hpe-oneview
    - ansible-modules
    - sdk
dependencies: []
