---
# defaults file for oneview_volume_facts
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_volume_facts/files/oneview_config.json"
volume_name: "Testing facts"     # set a volume name to run this example
snapshot_name: "Testing facts_20160823201021"  # set a snapshot name to run this example