---
galaxy_info:
  role_name: image_streamer_golden_image_facts
  author: Shanmugam M
  description: Ansible role to manage Golden Image facts resource.
  company: Hewlett Packard Enterprise
  license: Apache
  min_ansible_version: 2.9
  min_python_version: 3.4.2
  platforms: []
  galaxy_tags:
    - ansible
    - hpe-oneview
    - image-streamer
    - ansible-modules
    - sdk
dependencies: []